### ISSUE TITLE
[1.12] Crash when crafting items with the same item id

### ISSUE THREAD

**Issue by EmosewaGamer** [MoreThanHidden/RestrictedPortals#12]
When crafting an item with the same item id, but a different meta data, the client crashes:
https://pastebin.com/KV3DirPp

**Comment by MoreThanHidden** [comment]
Fixed in 1.12-1.6.1.

**Comment by MoreThanHidden** [comment]
![image](https://user-images.githubusercontent.com/1351964/29493474-49b514d2-85c9-11e7-8870-b6fcae53fafb.png)
