### ISSUE TITLE
[Suggestion] Can you add the following

### ISSUE THREAD

**Issue by ghost** [MoreThanHidden/RestrictedPortals#18]
I was wondering could you add support for other crafting benches to allow crafted items to be made in them so that people don't have to use just Vanilla Crafting bench cause as it sits now they can only unlock a Dim if the item is crafted in a Vanilla crafting bench.

TInker's Crafting Station
Extended Crafting

Thanks for taking a look into it

**Comment by remclave** [comment]
Other Crafting Tables as well from:
Random Things
Galacticraft Core
More Planets

If I find others, I will edit this entry.

**Comment by MoreThanHidden** [comment]
Fixed in 1.13 will look into back porting the changes to 1.12 if supported.
