### ISSUE TITLE
Restrict Portals Until Advancement?

### ISSUE THREAD

**Issue by Yourname942** [MoreThanHidden/RestrictedPortals#25]
Is there any possibility to have the option to restrict the player from entering dimension(s) X until unlocking advancement(s) Y?

It would be nice to choose if a player needs an item and/or an advancement in order to enter a given dimension. Thank you.

**Comment by MoreThanHidden** [comment]
That is how it works, but the mod dynamically generates advancements based on the config although you can override the unlock advancements with a data pack and that will unlock the dimensions.

**Comment by MoreThanHidden** [comment]
Example Data Pack attached.
[zCustom-RP-Datapack.zip](https://github.com/MoreThanHidden/RestrictedPortals/files/5080174/zCustom-RP-Datapack.zip)
![image](https://user-images.githubusercontent.com/1351964/90329185-026dcd80-dfd5-11ea-8c01-887bdefd4a20.png)

**Comment by MoreThanHidden** [comment]
Added to the [Wiki - Custom Advancement Datapacks](https://github.com/MoreThanHidden/RestrictedPortals/wiki/Custom-Advancement-Datapacks)
