### ISSUE TITLE
Enable Server-Side Only 1.12.2

### ISSUE THREAD

**Issue by MineCrak** [MoreThanHidden/RestrictedPortals#29]
Regarding Restricted Portals mod for Minecraft 1.12.2

Hello again. I am in great need of being able to use your mod as a server-side only mod for a new Server I am creating for the Cubic Chunks community. 

The Cubic Chunks mod now has an option allowing mc1.12.2 Forge CC servers to be connected to by mc 1.12.2 Vanilla non-forge clients. And in addition to this there is a Proxy tool chain that can further allow both Bedrock clients and Vanilla 1.7.10 thru Vanilla 1.16.2+ Java clients to also connect to and play on a 1.12.2 Java Forge CC server. 

The only condition is that any mods on the server side must actually act as server-side only mods and not require themselves to also be installed client-side. 

Barteks2x, CC dev, tells me that he thinks your mod might be able to act as a server-side only mod if it is just set as one. He gave me the following information regarding this:

"
The restricted portals mod should easily work as a server-side only mod if it was marked as such
just one line change here: 
[https://github.com/MoreThanHidden/RestrictedPortals/blob/1.12.x/src/main/java/morethanhidden/restrictedportals/RestrictedPortals.java#L23](https://github.com/MoreThanHidden/RestrictedPortals/blob/1.12.x/src/main/java/morethanhidden/restrictedportals/RestrictedPortals.java#L23)

just adding 

**acceptableRemoteVersions = "*"**

in there.
"

**Comment by MineCrak** [comment]
Barteks2x just made a test build doing what was mentioned above and so far it works!

Please compile and upload this new version and place onto curse.

**Comment by MineCrak** [comment]
Hi, our community could still get great use out of this on 1.12.2 as our servers still all use that version. 

Please release this updated version on curseforge so that we can include your mod in cf packs. :)

Thank you.

**Comment by MoreThanHidden** [comment]
I believe I already released server side only on 1.12 I'll make sure but think it's already done.
