### ISSUE TITLE
Problem when setting a block as required "item"

### ISSUE THREAD

**Issue by Mohron** [MoreThanHidden/RestrictedPortals#3]
Version: RestrictedPortals-1.9.4-0.5.jar
ClientLog: http://pastebin.com/gXrM1AMR
Config: 
```
general {
    S:"Crafted Items"=tconstruct:toolforge,extrautils2:AngelRing
    S:"Dimension IDs"=-1,1
    S:"Dimension Names"=Nether,End
}
```

I think it may be because on of the options I selected is a block and not and item. Either way it breaks the achievement screen completely and the achievement (only the tool forge one).

**Comment by MoreThanHidden** [comment]
No worries I can fix that easily, I'll have a look after work, I'll also look at including an easy way to update the achievement descriptions as-well, they used to be dynamic but had issues when porting to 1.9

**Comment by Mohron** [comment]
Will there be a new Curse build soon? Would love to get this fix in my pack/server.

**Comment by MoreThanHidden** [comment]
Currently under review, Uploaded it 2 hours ago.
![curse](https://cloud.githubusercontent.com/assets/1351964/16307094/9cb928fa-3992-11e6-80fc-253b2467af72.PNG)

**Comment by Mohron** [comment]
Ah, good to know! Thanks for you hard work :+1:

**Comment by Mohron** [comment]
Also ever since I set a block in the config, the achievement page is busted.  BetterAcheivements is installed as well.
![Achievements](https://s31.postimg.org/4sgr2gcaz/Portal_Restrict_Achievements.png)

**Comment by MoreThanHidden** [comment]
![rpa](https://cloud.githubusercontent.com/assets/1351964/16360806/ec20411e-3ba7-11e6-9017-b4813870a6a3.PNG)

**Comment by Mohron** [comment]
Then it has to be more specific that just setting the config to a block... I just disabled restricted portals and my achievements are fixed. Try having the first thing be an item, as it become the icon. Or if you want to can just see the problem [here](http://minecraft.curseforge.com/projects/rebel-uprising).

**Comment by MoreThanHidden** [comment]
Yeah all good, am working on a fix, seems to be modded items. regarding the crash looks like the versions or configs may be different on client and server? Will get the errors I can find sorted first, and add version checking to the server.

**Comment by Mohron** [comment]
The configs are the same. I control the modpack and server. Just let me know if I can help.

**Comment by MoreThanHidden** [comment]
Success!
![rpa](https://cloud.githubusercontent.com/assets/1351964/16362113/5012f7fe-3bd8-11e6-9ca2-53c6b52f5ad7.PNG)

**Comment by Mohron** [comment]
What a beauty!
