### ISSUE TITLE
Broken Shears?

### ISSUE THREAD

**Issue by benbenlaw** [MoreThanHidden/RestrictedPortals#34]
im not sure why this happens but with restriced portals other modded shears do not work

any ideas

**Comment by benbenlaw** [comment]
this applies to shears added by botania, ceramic shears and cyclic sheatrs

**Comment by benbenlaw** [comment]
also removeing the mod does not fix the issues so its really broken haha

**Comment by cech12** [comment]
Removing RestrictedPortals works for new games. 
But savegames stay broken. :/

**Comment by cech12** [comment]
Some thoughts and information:

* The shears mods are adding items to the forge:shears item tag. Maybe this tag is broken by your mod?!
* The [loot table changes by forge](https://github.com/MinecraftForge/MinecraftForge/tree/1.16.x/src/generated/resources/data/minecraft/loot_tables/blocks) are only used for shears for now.
* Maybe the datapack generation is changing something in the level.dat that breaks this behavior in the savegame?!

**Comment by MoreThanHidden** [comment]
Weird, I would assume manually creating a datapack of any kind would cause the same issue then? I'll do some testing.

**Comment by benbenlaw** [comment]
thanks buddy yeah its very strange thanks for the quick responce

**Comment by MoreThanHidden** [comment]
Ok worked out the issue somehow I'm reordering the datapacks:
![image](https://user-images.githubusercontent.com/1351964/106914258-cc1d3980-673f-11eb-88d3-317f0439ec47.png)

How it should look:
![image](https://user-images.githubusercontent.com/1351964/106914305-d93a2880-673f-11eb-824f-29ad10527654.png)

How it looks after either this mod or a few others that reload the same way are run:
![image](https://user-images.githubusercontent.com/1351964/106914008-911b0600-673f-11eb-9f7a-a6ca7bb1ff47.png)

Main issue is the order of forge and vanilla, I'll get this fixed up.

**Comment by benbenlaw** [comment]
ahh a least you know the issue thanks for finding the problem

**Comment by cech12** [comment]
I found this issue: https://github.com/MinecraftForge/MinecraftForge/issues/7644
Is it related to this problem?

**Comment by MoreThanHidden** [comment]
Probably, I've now fixed it by grabbing the enabled list out of the loader and just appending my Datapack, I'm just looking at reordering forge and vanilla for at least the next few versions to fix the corrupted worlds.

**Comment by benbenlaw** [comment]
oh nice well done :)

**Comment by MoreThanHidden** [comment]
Also fixed in Bluepower https://github.com/Qmunity/BluePower/commit/9085e1f45f9134f709f6f96009926b3cbf17127f

**Comment by Syrikal** [comment]
Hi! I'm looking to solve this issue with my mod; would you mind pointing me to your solution in your mod files? Thanks!
