### ISSUE TITLE
Server Crashes after 0.5.2 update:

### ISSUE THREAD

**Issue by Mohron** [MoreThanHidden/RestrictedPortals#4]
Mod: RestrictedPortals-1.9.4-0.5.2
Forge: forge-1.9.4-12.17.0.1976-universal
[Crash Report](http://pastebin.com/emsAtE0D)

After updating this the current version of the mod, the MC client loads fine. The server crashes with java.lang.NoClassDefFoundError. Is there a chance that part up the update is using a client-side only in the common proxy?

**Comment by MoreThanHidden** [comment]
Doesn't use a proxy due to simplifying the mod but I'll see what I can do.

**Comment by MoreThanHidden** [comment]
Should be good to go, is working in testing.

**Comment by Mohron** [comment]
Now getting an Internal Server Error
http://pastebin.com/Zv8Dd5xK

**Comment by MoreThanHidden** [comment]
Odd seems unrelated but will test this and #3 with a few mods and full server to client interaction.

**Comment by MoreThanHidden** [comment]
Seems to be related to not being able to load the modded items, let me know if your still getting the issue in 0.5.4
