### ISSUE TITLE
config doesn't read meta data for items?

### ISSUE THREAD

**Issue by SniperHauss89** [MoreThanHidden/RestrictedPortals#5]
Hello I am trying to utilize your mod and it works well to an extent because what I noticed is the config doesn't seem to want to read meta data for items and nearly all modded items have meta data variants anymore so I have tried a handful of things and they only the format that should work (for instance Botania:rune:1 should show a fire rune in the achievements window but it still shows the water rune that is the base Botania rune item. here is my config:

# Configuration file

general {
    S:"Crafted Items"=botania:rune:1,enderio:darkSteel_sword
    S:"Dimension IDs"=-1,1
    S:"Dimension Names"=Nether,End
}

any help would be appreciated :)

RestrictedPortals-1.9.4-0.5.4

note: actually after I updated to the latest build(1.9.4-0.5.4 from 1.9.4-0.5) it screwed up the achievements screen like in a previously closed issue. (yes I use better achievements)

**Comment by MoreThanHidden** [comment]
I think you'll find the achievements screen issue was due to the config but have added the support for metadata, uploaded to curse will need to wait for them to approve. Let me know if you still have issues after 0.5.5.

**Comment by SniperHauss89** [comment]
I figured as much with the achievements screen and I just tested it and it works great now. thanks a bunch and your very proficient. ^.^

(on a side note it still shows the unlocalized name eg. item.rune1.name where as using a modded item with no meta data registers just fine.)

**Comment by MoreThanHidden** [comment]
Hmm odd, the name looked to be working yesterday I'll have a look after work.

**Comment by MoreThanHidden** [comment]
0.5.6 is now available on Curse
