### ISSUE TITLE
chat message

### ISSUE THREAD

**Issue by Kashdeya** [MoreThanHidden/RestrictedPortals#7]
It would be nice for pack makers if we could change the chat message for when someone tryes to use the portal b4 crafting the item needed.

**Comment by MoreThanHidden** [comment]
I'll have a look when I get home from work but I believe this is already included in the Lang file, you can edit these localisations with minetweaker or I believe crafttweaker.

**Comment by MoreThanHidden** [comment]
Alright added to 1.11 version I'll back port to 1.10 seeing as that is the current popular version.
(Looks like the .lang file got bypassed at some point between 1.7.10 and 1.11)

**Comment by MoreThanHidden** [comment]
Probably not required anymore but all done, I'll compile and upload to Curse, let me know if you have issues. 

Format is "Please craft a %item% to enter the %dim%" as per the default.
%item% and %dim% arn't required but state the item that needs to be crafted and dimension.
