### ISSUE TITLE
Crash when clicking portal block with empty hand (1.7.10)

### ISSUE THREAD

**Issue by Sir-Chi** [MoreThanHidden/RestrictedPortals#8]
I'm using the latest version (0.3.2) for 1.7.10. The crash happens when I right click the portal block with an empty hand.

Here's the crash report
[crash-2016-12-21_15.04.51-client.txt](https://github.com/MoreThanHidden/RestrictedPortals/files/666664/crash-2016-12-21_15.04.51-client.txt)

Any help will be appreciated. Thanks - SC

**Comment by MoreThanHidden** [comment]
Not actively working on the 1.7.10 branch, but looks like a left over from when I used to detect if the key was right clicked on the portal for the achievement. I'll have a look now.

**Comment by Sir-Chi** [comment]
Ah thanks :)

**Comment by MoreThanHidden** [comment]
Will copy over to curse shortly.

**Comment by Sir-Chi** [comment]
Thank you. It's very appreciated!
